//login actions
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

//userAdmin actions

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"

export const FILL_FORM = "FILL_FORM"
export const CHECK_ID = "CHECK_ID"
export const UPDATE_USER = "UPDATE_USER"

//get all users
export const ALL_USER_REQUEST = "ALL_USER_REQUEST"
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"
export const UPDATE_ALL_USERS = "UPDATE_ALL_USERS"

//service actions
export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST"
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS"
export const CREATE_SERVICE_FAILURE = "CREATE_SERVICE_FAILURE"

//account actions
export const ALL_ACCOUNTS_REQUEST = "ALL_ACCOUNTS_REQUEST"
export const ALL_ACCOUNTS_SUCCESS = "ALL_ACCOUNTS_SUCCESS"
export const ALL_ACCOUNTS_FAILURE = "ALL_ACCOUNTS_FAILURE"

//favorite account
export const ALL_FAV_ACCOUNTS_REQUEST = "ALL_FAV_ACCOUNTS_REQUEST"
export const ALL_FAV_ACCOUNTS_SUCCESS = "ALL_FAV_ACCOUNTS_SUCCESS"
export const ALL_FAV_ACCOUNTS_FAILURE = "ALL_FAV_ACCOUNTS_FAILURE"