//login actions
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

//userAdmin actions

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE"

export const FILL_FORM = "FILL_FORM"
export const CHECK_ID = "CHECK_ID"
export const UPDATE_USER = "UPDATE_USER"

//get all users
export const ALL_USER_REQUEST = "ALL_USER_REQUEST"
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"
export const UPDATE_ALL_USERS = "UPDATE_ALL_USERS"

//service actions
export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST"
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS"
export const CREATE_SERVICE_FAILURE = "CREATE_SERVICE_FAILURE"
export const ALL_SERVICES_REQUEST = "ALL_SERVICES_REQUEST"
export const ALL_SERVICES_SUCCESS = "ALL_SERVICES_SUCCESS"
export const ALL_SERVICES_FAILURE = "ALL_SERVICES_FAILURE"
export const UPDATE_SERVICES_SUCCESS = "UPDATE_SERVICES_SUCCESS"
export const UPDATE_SERVICES_FAILUER= "UPDATE_SERVICES_FAILURE"

//account actions
export const ALL_ACCOUNTS_REQUEST = "ALL_ACCOUNTS_REQUEST"
export const ALL_ACCOUNTS_SUCCESS = "ALL_ACCOUNTS_SUCCESS"
export const ALL_ACCOUNTS_FAILURE = "ALL_ACCOUNTS_FAILURE"

//favorite account
export const ALL_FAV_ACCOUNTS_REQUEST = "ALL_FAV_ACCOUNTS_REQUEST"
export const ALL_FAV_ACCOUNTS_SUCCESS = "ALL_FAV_ACCOUNTS_SUCCESS"
export const ALL_FAV_ACCOUNTS_FAILURE = "ALL_FAV_ACCOUNTS_FAILURE"
export const CREATE_FAV_ACCOUNT_REQUEST = "CREATE_FAV_ACCOUNT_REQUEST"
export const CREATE_FAV_ACCOUNT_SUCCESS = "CREATE_FAV_ACCOUNT_SUCCESS"
export const CREATE_FAV_ACCOUNT_FAILURE = "CREATE_FAV_ACCOUNT_FAILURE"
export const UPDATE_FAV_ACCOUNTS = "UPDATE_FAV_ACCOUNTS"
export const UPDATE_FAV_ACCOUNTS_FAILURE = "UPDATE_FAV_ACCOUNTS_FAILURE"
export const NO_MONEY_TRANSACTION_FAILURE = "NO_MONEY_TRANSACTION_FAILURE"

//search account 
export const SEARCH_ACCOUNTS_REQUEST = "SEARCH_ACCOUNTS_REQUEST"
export const SEARCH_ACCOUNTS_SUCCESS = "SEARCH_ACCOUNTS_SUCCESS"
export const SEARCH_ACCOUNTS_FAILURE = "SEARCH_ACCOUNTS_FAILURE"

//search account 
export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE"

//transaction
export const TRANSACTION_REQUEST = "TRANSACTION_REQUEST"
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS"
export const TRANSACTION_FAILURE = "TRANSACTION_FAILURE"

//payments 
export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST"
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS"
export const CREATE_PAYMENT_FAILURE = "CREATE_PAYMENT_FAILURE"
export const ALL_USER_PAYMENTS_REQUEST = "ALL_USER_PAYMENTS_REQUEST"
export const ALL_USER_PAYMENTS = "ALL_USER_PAYMENTS"
export const ALL_USER_PAYMENTS_FAILURE = "ALL_USER_PAYMENTS_FAILURE"